services:
  db:
    image: postgres:15-alpine
    container_name: traefik-stats-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: traefik_stats
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

  worker:
    build: .
    container_name: traefik-stats-worker
    restart: unless-stopped
    depends_on:
      - db
    entrypoint: ["python", "worker.py"]
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/traefik_stats
      RETENTION_DAYS: 30
    volumes:
      - /home/mattia/proxy/traefik/access.log:/app/logs/access.log:ro
      - /home/mattia/proxy/data/crowdsec/data/GeoLite2-City.mmdb:/app/geoip/city.mmdb:ro
      - /home/mattia/proxy/data/crowdsec/data/GeoLite2-ASN.mmdb:/app/geoip/asn.mmdb:ro
    networks:
      - proxy

  traefik-stats:
    build: .
    container_name: traefik-stats
    restart: unless-stopped
    depends_on:
      - db
    entrypoint: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/traefik_stats
    volumes:
      - /home/mattia/proxy/data/crowdsec/data/GeoLite2-City.mmdb:/app/geoip/city.mmdb:ro
    networks:
      - proxy
    ports:
      - "8501:8501"

networks:
  proxy:
    external: true
