[theme]
primaryColor = "#00CC96"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"

[runner]
magicEnabled = true
fastReruns = true

[client]
caching = true
toolbarMode = "minimal"
